### ISSUE TITLE
Database Not Found

### ISSUE THREAD

**Issue by daothinh** [Hritikpatel/InsecureTrust_Bank#2]
Can you upload the project's database?

**Comment by Hritikpatel** [comment]
I appreciate your response regarding the project's database. I've updated the SQL commands in the [README.md](https://github.com/Hritikpatel/InsecureTrust_Bank/blob/main/README.md) to create the database and add dummy data. 

If I encounter any issues with the database, I will be sure to continue the discussion in this thread or create a new issue as needed. Thank you for your assistance, and I will consider this issue closed for now.

**Comment by daothinh** [comment]
Thanks!
